apiVersion: v1
kind: Service
metadata:
  name: rabbit-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: rabbit
  ports:
    - name: rabbit-cluster
      port: 5672
      targetPort: 5672
    - name: rabbit-management
      port: 15672
      targetPort: 15672
